localstack/moto

moto/sns/models.py

I hope I'm going about this the right way...
This is related to localstack issue [#1279](https://github.com/localstack/localstack/issues/1279) which I just opened.
Apologies, but this is actually the first python I've ever written so this may be completely wrong and I didn't feel ambitious to write a test just yet.  The gist is the .net sdk sends empty string on the first list topics request during certain operations (mentioned in issue [#1279](https://github.com/localstack/localstack/issues/1279)) and this is failing here as empty string is not None and cannot be parsed as int.

handles empty string in addition to None

---

IMPLEMENTATION_COVERAGE.md
moto/ec2/models.py
moto/ec2/responses/vpcs.py
tests/test_ec2/test_vpcs.py

Implements the following routes:
* describe-vpc-classic-link
* enable-vpc-classic-link
* disable-vpc-classic-link
* describe-vpc-classic-link-dns-support
* enable-vpc-classic-link-dns-support
* disable-vpc-classic-link-dns-support
The above routes allowed me to deploy a vpc using terraform with localstack.

Adds basic support for vpc-classic-link and vpc-classic-link-dns-support

---

moto/ec2/resources/amis.json

Solves issue in testing EKS where EKS optimised AMIs are largely expected.
I managed to work this out thanks to this answer in https://github.com/localstack/localstack/issues/3714#issuecomment-798811876

Update amis.json to support EKS AMI mocks

---

moto/s3/responses.py

**Fixed**
- In the above precondition check - The value for `if_match`  was <etag> instead of "<etag>" (quotes were missing) which was leading code to execute unwanted conditions
**Terraform test**
- TestAccAWSS3BucketObject_metadata

fixed precondition check for etags in s3

---

moto/s3/responses.py

**Fixed**
- Fixed S3 encryption response `BucketKeyEnabled` was always returning `true`
**Reproducible Code**
```
resource "aws_s3_bucket" "arbitrary" {
bucket = "test-1603981"
server_side_encryption_configuration {
rule {
apply_server_side_encryption_by_default {
sse_algorithm = "aws:kms"
}
}
}
}
```

fix s3 encryption response

---

moto/events/models.py
tests/test_events/test_event_pattern.py

Change `__str__` to avoid `None` when call string upon the class. This avoids `null` in the json response and makes [TestAccAWSCloudWatchEventArchive_basic](https://github.com/hashicorp/terraform-provider-aws/blob/72e623415ce30dfa463aa0cac7d3ef433b262824/aws/resource_aws_cloudwatch_event_archive_test.go#L74) pass

fix(events): Empty string instead of `null` in EventPattern

---

moto/logs/models.py
moto/logs/responses.py
tests/test_logs/test_logs.py
tests/test_logs/test_models.py

This PR adds the `kms_key_id` attribute in `LogGroup` and also ads the mentioned attribute in the describe response, as suggested on the AWS official API spec. 
It also parses the `kmsKeyId` from the `logs/CreateLogGroup` request. 
Docs: 
- https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_CreateLogGroup.html
- https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DescribeLogGroups.html
This change makes the `TestAccAWSCloudwatchLogGroupDataSource_kms` pass. 
Something to notice is that the whole `TestAccAWSCloudwatchLogGroupDataSource` suite is passing now!

feat(logs): Add `kmsKeyId` into `LogGroup` entity.

---

moto/events/models.py
moto/events/responses.py
tests/test_events/test_events.py

This PR adds the `describe_connection` and `delete_connection` to the events Response and Backend. 
Docs: 
- https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_DeleteConnection.html
- https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_DescribeConnection.html
This change makes the `TestAccAWSDataSourceCloudwatch_Event_Connection_basic` pass.

feat(events): Add describe and delete connection

---

moto/ec2/models.py
moto/ec2/responses/__init__.py
moto/ec2/responses/transit_gateway_route_tables.py
moto/ec2/utils.py

**Added**
- API_CreateTransitGatewayRouteTable
- API_DescribeTransitGatewayRouteTable
- API_DeleteTransitGatewayRouteTable
- Expanded API_DescribeTransitGateway for extra filter support
- Updated `get_prefix(...)` to support `tgw-rtb`
**Tested with**
- Tested by applying multiple times, updating, destroying
```
resource "aws_ec2_transit_gateway" "example" {
description                     = "test description"
default_route_table_propagation = "disable"
dns_support                     = "disable"
tags = {
"Name"     = "testTransitGateway",
"testKey" = "testValueTansit"
}
}
resource "aws_ec2_transit_gateway_route_table" "example" {
transit_gateway_id = aws_ec2_transit_gateway.example.id
tags = {
"testKey" = "testValue"
}
}
```

added support for transit gateway route tables

---

moto/ec2/models.py
moto/ec2/responses/transit_gateway_route_tables.py

**Follow Up PR**
#27 
**Added**
- Support for passing transit gateway route table id in describe api
**TF Test Fix**
- TestAccAWSEc2TransitGatewayRouteTableDataSource_ID

support for passing transit gateway route table id in describe api, minor refractoring

---

moto/acm/models.py

Fixes https://github.com/localstack/localstack/issues/4313
Current setup of ACM does not take `AWS_DEFAULT_REGION` when importing a certificate:
```
$ awslocal acm import-certificate --certificate fileb://cert.pem --private-key fileb://privkey.pem 
{
"CertificateArn": "arn:aws:acm:cn-northwest-1:000000000000:certificate/613cfbc8-3c46-4422-b041-9da11f8a394a"
}
```
After the fix:
```
awslocal acm import-certificate --certificate fileb://cert.pem --private-key fileb://privkey.pem 
{
"CertificateArn": "arn:aws:acm:us-east-1:000000000000:certificate/31f799f8-bd19-4f5b-aabb-ccee32d87689"
}
```

Fix: ACM import certificate region

---

moto/ec2/models.py
moto/ec2/responses/transit_gateway_attachments.py
moto/ec2/responses/virtual_private_gateways.py
moto/ec2/responses/vpn_connections.py
moto/ec2/utils.py
tests/test_ec2/test_vpn_connections.py

- `TransitGatewayVpcAttachment` objects are not being stored in the backend.
- `TransitGateway` support in `VpnConnection`.
- XML response of `CreateVpnConnection` and `DescribeVpnConnection`.
- `DeleteVpnConnection` logic. State needed to be 'deeted' instead of deleting actual object. **TODO**: delete `VpnConnection` object in clean up process.
- Fixed 'VpnGateway'. Still couple of methods are remmaining.
- Support for TransitGatewayAttachment of `VpnConnection`. (Attachment will directly be made right after creating `VpnConnection`).
- API `DescribeTransitGatewayAttachments`.
- API `DescribeTransitGatewayVpcAtatchments`.
- method `create_transit_gateway_vpn_attachment()` to create `TransitGatewayVpnConnectionAttachment`.
- VpnConnection
```terraform
resource "aws_ec2_transit_gateway" …
```

Added support for TGW-VPN-attachment

---

moto/events/models.py

Work done
---
Add a new attribute `_filter_raw` in `EventPattern` just to make terraform happy when checking for plan. 
Open to discuss the approach :smile: 
Test
---
<details>
<summary>How was this failing before? </summary>
<p>
```
resource_aws_cloudwatch_event_archive_test.go:110: Step 2/2 error: After applying this test step, the plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "aws_cloudwatch_event_archive" "test" {
~ event_pattern    = jsonencode( # whitespace changes
{
source = [
"company.team.service",
]
}
)
id               = "tf-acc-test-2478843715857287063"
name             = …
```

fix(events): store raw filter representation for event pattern

---

moto/events/models.py
moto/events/responses.py

Work Done
---
This PR adds the `delete_api_destination`, `describe_api_destination` and `update_api_destination` to the events Response and Backend.
Also refactors creation to include `InvocationRateLimitPerSecond` 
Docs:
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_CreateApiDestination.html
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_DeleteApiDestination.html
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_DescribeApiDestination.html
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_UpdateApiDestination.html
Test
---

feat(events): Add describe, update & delete api destination

---

moto/batch/models.py

This commit extracts the run_batch_container method containing the docker client run call to run a batch container, for easier patching.

extract the run_batch_container method out of the run method

---

moto/sqs/models.py

Currently, when filtering for message attributes mutates the SQS State by deleting all non-filtered attributes. This change creates a deepcopy of a message and only applies the filter on the copy.

Small fix to not overwrite message attributes when being filtered

---

README.md

with this change, you can stay in `localstack` branch and run all other commands without changing the branch

readme: use less git checkouts for release

---

Makefile
setup.py
tests/test_cloudformation/test_validate.py

Remove the dependency to `cfn-lint`, to save some space in the LocalStack Docker image:
```
138M	/opt/code/localstack/.venv/lib/python3.10/site-packages/cfnlint
```
This is safe to remove for our purposes - the only place where cfnlint is imported is inside [validate_template_cfn_lint(..)](https://github.com/spulec/moto/blob/e911341e6ad1bfe7f3930f38c36b26b25cdb0f94/moto/cloudformation/utils.py#L62-L64), which we're not currently making use of (our CloudFormation provider returns a mocked result for `validate_template(..)`).
As discussed - if and when we introduce `cfn-lint` for our own CloudFormation implementation, we can prune the `cfnlint/data/CloudSpecs/...` folder and leave only `us-east-1.json` as the canonical region in there (reducing the total size to ~14MB). There are some minor …

Remove dependency to cfn-lint

---

moto/kms/models.py
tests/test_kms/test_model.py

Addresses https://github.com/localstack/localstack/issues/6471
KMS is supposed to allow to use ARNs of key aliases for encryption/decryption. Unfortunately, while it is true in the upstream moto repository, in our fork it was broken.
This PR simply replaces one line in models.py with the corresponding liтe from the upstream repository. And copies from the upstream repository one test file as-is, as that file has tests that cover this behavior.

Making it possible to encrypt using ARNs of KMS key aliases.

---

moto/elbv2/models.py

A user encountered an error while trying to set up an ALB resource with Terraform:
```
Error: failure configuring LB attributes: :
│       status code: 400, request id: 7a62c49f-347e-4fc4-9331-6e8eEXAMPLE
│
│   with aws_lb.this,
│   on [load_balancer.tf](http://load_balancer.tf/) line 58, in resource "aws_lb" "this":
│   58: resource "aws_lb" "this" {  
resource "aws_lb" "this" {
name               = "nginx-lb"
internal           = false
load_balancer_type = "application"
security_groups    = [aws_security_group.db_instance.id]
subnets            = data.aws_subnets.default.ids
enable_deletion_protection = true
tags = {
Environment = "production"
}
}
```
Error message from Terraform:
```json
{"@level":"debug","@message":"-----------------------------------------------------","@module":"prov …
```

fix ELBv2 - add valid attribute and fix set_ip_address_type possibles values

---

moto/batch/models.py

Mypy has been enabled upstream, but the pipeline is failing because one of our patches includes an untyped function call. This PR adds types to that function so that the pipeline passes again.

Fix mypy errors
